- hosts: all
  user: ansible
  become: True
  tasks:
   - name: Install all the packages
     apt:
         name: ['git', 'vim', 'openssh-client', 'ecryptfs-utils', 'cryptsetup', 'nextcloud-desktop', 'nautilus-nextcloud', 'clamav', 'clamav-daemon', 'thonny']
         state: present
         update_cache: True
   - name: Download ID-Software
     get_url:
        url: "https://installer.id.ee/media/install-scripts/install-open-eid.sh"
        dest: ~/Downloads/install-open-eid.sh
   - name: Execute the script
     shell: ~/Downloads/install-open-eid.sh


