- hosts: all
  user: ansible
  become: True
  tasks:
   - name: Install all the packages
     apt:
         name: ['git', 'vim', 'openssh-client', 'ecryptfs-utils', 'cryptsetup', 'nextcloud-desktop', 'nautilus-nextcloud', 'clamav', 'clamav-daemon']
         state: present
         update_cache: True
